from .deletion import DELETION_DICT
from .letter_cases import LETTER_LOWER2UPPER_DICT, LETTER_UPPER2LOWER_DICT
from .shift_key import SHIFT_KEY_DICT, SHIFT_KEY_FORWARD_DICT, SHIFT_KEY_REVERSE_DICT
from .space import SPACE_DICT
from .keyboard_typo import KEYBOARD_TYPO_DICT, KEYBOARD_TYPO_ADVANCED_DICT